[package]
name = "blog_os"
version = "0.1.0"
authors = ["Jonny Sparrenhök <Jonnysp@kth.se>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
volatile = "0.1.0"
rlibc = "0.1.4"
spin = "0.4.5"
multiboot2 = "0.1.0"
bitflags = "0.9.1"
x86_64 = "0.1.2"
once = "0.3.3"
linked_list_allocator = "0.4.2"
